// Code generated by protoc-gen-go. DO NOT EDIT.
// source: log.proto

package proto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Log_Level int32

const (
	Log_UnKnown Log_Level = 0
	Log_Info    Log_Level = 1
	Log_Debug   Log_Level = 2
	Log_Warning Log_Level = 3
	Log_Error   Log_Level = 4
)

var Log_Level_name = map[int32]string{
	0: "UnKnown",
	1: "Info",
	2: "Debug",
	3: "Warning",
	4: "Error",
}

var Log_Level_value = map[string]int32{
	"UnKnown": 0,
	"Info":    1,
	"Debug":   2,
	"Warning": 3,
	"Error":   4,
}

func (x Log_Level) String() string {
	return proto.EnumName(Log_Level_name, int32(x))
}

func (Log_Level) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_a153da538f858886, []int{0, 0}
}

type Log struct {
	App                  string    `protobuf:"bytes,1,opt,name=app,proto3" json:"app,omitempty"`
	Module               string    `protobuf:"bytes,2,opt,name=module,proto3" json:"module,omitempty"`
	Level                Log_Level `protobuf:"varint,3,opt,name=level,proto3,enum=proto.Log_Level" json:"level,omitempty"`
	TraceId              string    `protobuf:"bytes,4,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	Message              []byte    `protobuf:"bytes,5,opt,name=message,proto3" json:"message,omitempty"`
	Exception            []byte    `protobuf:"bytes,6,opt,name=exception,proto3" json:"exception,omitempty"`
	UserIp               string    `protobuf:"bytes,7,opt,name=user_ip,json=userIp,proto3" json:"user_ip,omitempty"`
	ExecTime             int32     `protobuf:"varint,8,opt,name=exec_time,json=execTime,proto3" json:"exec_time,omitempty"`
	CreateTime           string    `protobuf:"bytes,9,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *Log) Reset()         { *m = Log{} }
func (m *Log) String() string { return proto.CompactTextString(m) }
func (*Log) ProtoMessage()    {}
func (*Log) Descriptor() ([]byte, []int) {
	return fileDescriptor_a153da538f858886, []int{0}
}

func (m *Log) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Log.Unmarshal(m, b)
}
func (m *Log) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Log.Marshal(b, m, deterministic)
}
func (m *Log) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Log.Merge(m, src)
}
func (m *Log) XXX_Size() int {
	return xxx_messageInfo_Log.Size(m)
}
func (m *Log) XXX_DiscardUnknown() {
	xxx_messageInfo_Log.DiscardUnknown(m)
}

var xxx_messageInfo_Log proto.InternalMessageInfo

func (m *Log) GetApp() string {
	if m != nil {
		return m.App
	}
	return ""
}

func (m *Log) GetModule() string {
	if m != nil {
		return m.Module
	}
	return ""
}

func (m *Log) GetLevel() Log_Level {
	if m != nil {
		return m.Level
	}
	return Log_UnKnown
}

func (m *Log) GetTraceId() string {
	if m != nil {
		return m.TraceId
	}
	return ""
}

func (m *Log) GetMessage() []byte {
	if m != nil {
		return m.Message
	}
	return nil
}

func (m *Log) GetException() []byte {
	if m != nil {
		return m.Exception
	}
	return nil
}

func (m *Log) GetUserIp() string {
	if m != nil {
		return m.UserIp
	}
	return ""
}

func (m *Log) GetExecTime() int32 {
	if m != nil {
		return m.ExecTime
	}
	return 0
}

func (m *Log) GetCreateTime() string {
	if m != nil {
		return m.CreateTime
	}
	return ""
}

type Response struct {
	ErrorCode            int32    `protobuf:"varint,1,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_a153da538f858886, []int{1}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetErrorCode() int32 {
	if m != nil {
		return m.ErrorCode
	}
	return 0
}

func (m *Response) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterEnum("proto.Log_Level", Log_Level_name, Log_Level_value)
	proto.RegisterType((*Log)(nil), "proto.Log")
	proto.RegisterType((*Response)(nil), "proto.Response")
}

func init() { proto.RegisterFile("log.proto", fileDescriptor_a153da538f858886) }

var fileDescriptor_a153da538f858886 = []byte{
	// 335 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x90, 0xdf, 0x4e, 0xab, 0x40,
	0x10, 0xc6, 0x4b, 0x81, 0x02, 0xd3, 0x93, 0x73, 0xc8, 0x5c, 0x1c, 0xd7, 0x7f, 0x91, 0x90, 0x68,
	0xb8, 0x6a, 0x62, 0x7d, 0x02, 0x53, 0xbd, 0x68, 0xe4, 0x8a, 0x6a, 0xbc, 0x24, 0x14, 0x46, 0x24,
	0x81, 0xdd, 0xcd, 0x42, 0xd5, 0x07, 0xf4, 0xc1, 0xcc, 0x2e, 0x6d, 0xea, 0x15, 0xf3, 0xfd, 0xbe,
	0x99, 0x61, 0xf6, 0x83, 0xa0, 0x15, 0xf5, 0x42, 0x2a, 0x31, 0x08, 0x74, 0xcd, 0x27, 0xfe, 0x9e,
	0x82, 0x9d, 0x8a, 0x1a, 0x43, 0xb0, 0x0b, 0x29, 0x99, 0x15, 0x59, 0x49, 0x90, 0xe9, 0x12, 0xff,
	0xc3, 0xac, 0x13, 0xd5, 0xae, 0x25, 0x36, 0x35, 0x70, 0xaf, 0xf0, 0x06, 0xdc, 0x96, 0x3e, 0xa8,
	0x65, 0x76, 0x64, 0x25, 0x7f, 0x97, 0xe1, 0xb8, 0x6f, 0x91, 0x8a, 0x7a, 0x91, 0x6a, 0x9e, 0x8d,
	0x36, 0x9e, 0x82, 0x3f, 0xa8, 0xa2, 0xa4, 0xbc, 0xa9, 0x98, 0x63, 0x36, 0x78, 0x46, 0xaf, 0x2b,
	0x64, 0xe0, 0x75, 0xd4, 0xf7, 0x45, 0x4d, 0xcc, 0x8d, 0xac, 0xe4, 0x4f, 0x76, 0x90, 0x78, 0x01,
	0x01, 0x7d, 0x95, 0x24, 0x87, 0x46, 0x70, 0x36, 0x33, 0xde, 0x11, 0xe0, 0x09, 0x78, 0xbb, 0x9e,
	0x54, 0xde, 0x48, 0xe6, 0x8d, 0x37, 0x69, 0xb9, 0x96, 0x78, 0xae, 0xc7, 0xa8, 0xcc, 0x87, 0xa6,
	0x23, 0xe6, 0x47, 0x56, 0xe2, 0x66, 0xbe, 0x06, 0xcf, 0x4d, 0x47, 0x78, 0x05, 0xf3, 0x52, 0x51,
	0x31, 0xd0, 0x68, 0x07, 0x66, 0x12, 0x46, 0xa4, 0x1b, 0xe2, 0x7b, 0x70, 0xcd, 0xe5, 0x38, 0x07,
	0xef, 0x85, 0x3f, 0x71, 0xf1, 0xc9, 0xc3, 0x09, 0xfa, 0xe0, 0xac, 0xf9, 0x9b, 0x08, 0x2d, 0x0c,
	0xc0, 0x7d, 0xa0, 0xed, 0xae, 0x0e, 0xa7, 0xba, 0xe3, 0xb5, 0x50, 0xbc, 0xe1, 0x75, 0x68, 0x6b,
	0xfe, 0xa8, 0x94, 0x50, 0xa1, 0x13, 0xaf, 0xc0, 0xcf, 0xa8, 0x97, 0x82, 0xf7, 0x84, 0x97, 0x00,
	0xa4, 0x71, 0x5e, 0x8a, 0x8a, 0x4c, 0xa2, 0x6e, 0x16, 0x18, 0xb2, 0x12, 0x15, 0xfd, 0x7e, 0xfc,
	0x18, 0xec, 0x41, 0x2e, 0x6f, 0xc1, 0x4f, 0x45, 0xbd, 0x19, 0x8a, 0xfe, 0x1d, 0xaf, 0xc1, 0xd9,
	0x10, 0xaf, 0x10, 0x8e, 0xf1, 0x9e, 0xfd, 0xdb, 0xd7, 0x87, 0x3f, 0xc5, 0x93, 0xed, 0xcc, 0x90,
	0xbb, 0x9f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x94, 0x5e, 0x76, 0x24, 0xd9, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// LogStashClient is the client API for LogStash service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type LogStashClient interface {
	Send(ctx context.Context, in *Log, opts ...grpc.CallOption) (*Response, error)
}

type logStashClient struct {
	cc *grpc.ClientConn
}

func NewLogStashClient(cc *grpc.ClientConn) LogStashClient {
	return &logStashClient{cc}
}

func (c *logStashClient) Send(ctx context.Context, in *Log, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/proto.LogStash/Send", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LogStashServer is the server API for LogStash service.
type LogStashServer interface {
	Send(context.Context, *Log) (*Response, error)
}

// UnimplementedLogStashServer can be embedded to have forward compatible implementations.
type UnimplementedLogStashServer struct {
}

func (*UnimplementedLogStashServer) Send(ctx context.Context, req *Log) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Send not implemented")
}

func RegisterLogStashServer(s *grpc.Server, srv LogStashServer) {
	s.RegisterService(&_LogStash_serviceDesc, srv)
}

func _LogStash_Send_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Log)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LogStashServer).Send(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.LogStash/Send",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LogStashServer).Send(ctx, req.(*Log))
	}
	return interceptor(ctx, in, info, handler)
}

var _LogStash_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.LogStash",
	HandlerType: (*LogStashServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Send",
			Handler:    _LogStash_Send_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "log.proto",
}
